# Generated by Django 4.2.1 on 2023-06-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctors_first_name_doctors_doctor_first_name_and_more'),
        ('bloodbank', '0003_patients_patient_doctor'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointments_patients',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bloodbank.patients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointments_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors'),
        ),
    ]
