# Generated by Django 4.2.1 on 2023-07-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_appointments_patients_appointments_appointments_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointments_date',
            field=models.DateField(default='2023-05-10'),
            preserve_default=False,
        ),
    ]
