# Generated by Django 4.2.1 on 2023-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctors_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doctors_first_name', models.CharField(max_length=50)),
                ('doctors_last_name', models.CharField(max_length=50)),
                ('doctors_type_blood', models.CharField(max_length=50)),
            ],
        ),
    ]
