# Generated by Django 4.2.1 on 2023-06-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_doctors_first_name_doctors_doctor_first_name_and_more'),
        ('bloodbank', '0002_rename_patient_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors'),
            preserve_default=False,
        ),
    ]
